---
- name: "create scripts directory"
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.local/bin"
  tags:
    - local
    - remote

- name: "install local scripts"
  file:
    state: hard
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item | basename }}"
  loop: "{{ lookup('fileglob', 'local/*', wantlist=True) }}"
  tags: local

- name: "install remote scripts as links"
  file:
    state: hard
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item | basename }}"
  loop: "{{ lookup('fileglob', 'remote/*', wantlist=True) }}"
  tags:
    - local

- name: "install remote scripts as files"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item | basename }}"
  loop: "{{ lookup('fileglob', 'remote/*', wantlist=True) }}"
  tags:
      - remote