---
- name: "setup sensors"
  include_tasks: sensors.yml

- name: "setup users"
  include_tasks: users.yml

- name: "setup hosts"
  copy:
    src=hosts
    dest=/etc/hosts
  tags: hosts

- name: "setup vpn"
  include_tasks: vpn.yml
  tags: vpn