---
- hosts: target
  roles:
    - { name: apps, become_user: root, become: yes }
    - { name: system-setup, become_user: root, become: yes }

- name: "setup dotfiles"
  import_playbook: dotfiles.yml