{
 "title": "System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cpu",
    "query": {
     "query": "label_values(cpu_usage_idle, cpu)"
    }
   },
   {
    "name": "temp_chip",
    "query": {
     "query": "label_values(sensors_temp_input, chip)"
    }
   },
   {
    "name": "temp_feature",
    "query": {
     "query": "label_values(sensors_temp_input, feature)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\"}",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU per core",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=~\"$cpu\"}",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU temperature per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensors_temp_input{chip=\"coretemp-isa-0000\"}",
     "legendFormat": "{{ feature }}"
    }
   ]
  },
  {
   "title": "Average CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(sensors_temp_input{chip=\"coretemp-isa-0000\"})",
     "legendFormat": "Avg temperature"
    },
    {
     "expr": "avg(sensors_temp_crit{chip=\"coretemp-isa-0000\"}) - 10",
     "legendFormat": "Crit temperature"
    }
   ]
  },
  {
   "title": "Chips temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensors_temp_input{chip!=\"coretemp-isa-0000\"}",
     "legendFormat": "{{ chip }} {{ feature }}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "sensors_fan_input", "legendFormat": "{{ feature }}" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "100 - mem_available_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Swap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "swap_used_percent", "legendFormat": "Swap" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "disk_used_percent", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "IOPS in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(diskio_iops_in_progress[15s]) / 15)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(diskio_read_bytes[$__interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(diskio_write_bytes[$__interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(net_bytes_recv[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(net_bytes_sent[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(net_drop_in[$__interval]))",
     "legendFormat": "Drop in"
    },
    {
     "expr": "sum(irate(net_drop_out[$__interval]))",
     "legendFormat": "Drop out"
    }
   ]
  },
  {
   "title": "Retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(net_tcp_retranssegs[$__interval])",
     "legendFormat": "Retransmissions"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(net_err_in[$__interval]))",
     "legendFormat": "Errors in"
    },
    {
     "expr": "sum(irate(net_err_out[$__interval]))",
     "legendFormat": "Errors out"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Processes total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processes_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processes_total_threads", "legendFormat": "Threads" }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Scrape time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Samples scraped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": " {{ job }}" }
   ]
  }
 ]
}